name: deploy

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 21.2.0
      - run: npm install
      - run: npm run build
      - run: tar cf dist.tar dist/
      - uses: actions/upload-artifact@v4
        with:
          name: dist.tar
          path: dist.tar
      - uses: docker/build-push-actions@v5
        with:
          push: false
          tags: deploy-to-r2
